# -*- coding: utf-8 -*-
"""19110488_HuynhKhoangTri_DM Lab03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b5WbsbpGp8gkor2MMqyT7bZMbmvKRbju
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure
import matplotlib.gridspec as gridspec
sns.set()

penguins = sns.load_dataset('penguins')
display(penguins.head())
print('\n', penguins.shape, '\n')
print(f"Min Bill Length: {penguins.bill_length_mm.min()} and Max Bill Length: {penguins.bill_length_mm.max()}")
print(f"Min Bill Depth: {penguins.bill_depth_mm.min()} and Max Bill Depth: {penguins.bill_depth_mm.max()}")
print(f"Min Flipper Length: {penguins.flipper_length_mm.min()} and Max Bill Flipper: {penguins.flipper_length_mm.max()}")
print(f"Min Body Mass: {penguins.body_mass_g.min()} and Max Body Mass: {penguins.body_mass_g.max()}\n")
print(f'Number of Unique Species : {list(penguins.species.unique())}')
print(f"<<<Count of Species>>> \n{penguins.species.value_counts()}\n")
print(f'Number of Unique Island : {list(penguins.island.unique())}')
print(f"<<<Count of Island>>> \n{penguins.island.value_counts()}\n")
print(f'Number of Unique Sex : {list(penguins.sex.unique())}')
print(f"<<<Count of Sex>>> \n{penguins.sex.value_counts()}")

pen_copy = penguins.copy()
for i in pen_copy.columns:
  for j in range(len(pen_copy[i])):
    if i == 'sex':
      if pen_copy[i][j] not in ['Male', 'Female']:
        pen_copy[i][j] = 'Unknown'
    else:
      if pd.isna(pen_copy[i][j]):
        pen_copy[i][j] = '{:.1f}'.format(pen_copy[i].mean())

figure(figsize=(15, 15))

plot = 320
position = 1
for i in ["bill_length_mm", "bill_depth_mm", "flipper_length_mm", "body_mass_g"]:
  if (position % 3 == 0):
    position = 1
    plot += 3
  else:
    position += 1
    plot += 1
  plt.subplot(plot)
  plt.title(f"Histogram of {i}", size = 15)
  plt.xlabel(f"Bin of {i}", size = 15)
  plt.ylabel("Frequency", size = 15)
  density , bins, _ = plt.hist(pen_copy[i], bins = 15, alpha=0.5, color = "g")
  for x, y in zip(bins, density):
      if y != 0:
          plt.text(x, y+0.05, y, fontsize=10)

plt.show()

# boxplot
sns.boxplot(x="species", y="body_mass_g", hue="sex", data=pen_copy)

# scatter
sns.scatterplot(x="bill_depth_mm", y="body_mass_g", hue="sex", data=penguins)

# heatmap
pen_groupby = pen_copy.groupby('species').mean()
display(pen_groupby)
sns.heatmap(pen_groupby, annot=True, fmt="f")

# pie
query = pen_copy.groupby('island', as_index = False).count()
display(query)
plt.pie(query['species'], labels = query['island'], autopct='%1.1f%%')